### ISSUE TITLE
Terminal Color in Moegi Dark

### ISSUE THREAD

**Issue by Vikingama** [moegi-design/vscode-theme#10]
![Code-2022-12-20-12 22 36](https://user-images.githubusercontent.com/26019582/208667130-21b1040e-a657-4907-b0a6-e82292ebeae1.png)

**Comment by ddiu8081** [comment]
Maybe fixed in v0.4.2

**Comment by Vikingama** [comment]
Yes, Thank you

**Comment by Vikingama** [comment]
<img width="477" alt="Code-2022-12-21-01 14 05" src="https://user-images.githubusercontent.com/26019582/208797425-f84ae28f-0bca-4c8b-b1cb-4a91f04fbc67.png">
