### ISSUE TITLE
Mutables in Rust are blacked out

### ISSUE THREAD

**Issue by orcharddu** [moegi-design/vscode-theme#12]
* Mutables in Rust are blacked out while Vitesse version displays correctly.
* Consider giving operator `&` a colour for Rust?
* Vote for a black Vitnesse version!

Cheers

<img width="973" alt="a" src="https://user-images.githubusercontent.com/14195908/209246552-7f5a7a7f-6631-4da8-9295-ba4d5c07d349.png">
<img width="966" alt="b" src="https://user-images.githubusercontent.com/14195908/209246565-dbe3d4b2-f698-4974-92b9-9bf8ef22c1ab.png">

**Comment by ddiu8081** [comment]
Seems to be fixed in `v0.4.4`. Thanks for your code and comparison, they helped me a lot!

<img width="636" alt="ScreenShot 2022-12-29 at 01 47 44@2x" src="https://user-images.githubusercontent.com/1998168/209852288-4f5b1531-d6de-4c0c-a279-2c3b87c8d853.png">
