### ISSUE TITLE
菜单配色优化建议

### ISSUE THREAD

**Issue by sechi747** [moegi-design/vscode-theme#13]
p1为`Vitesse Black`, p2为`Moegi Black`  
禁用状态下的菜单项观感有些不太好
![image](https://user-images.githubusercontent.com/73569598/210501918-a6daf87a-c0f7-43dc-9000-0ed79ff442fd.png)
![image](https://user-images.githubusercontent.com/73569598/210501955-d3bcba31-3e1d-4558-bb80-640b46936d4c.png)

**Comment by ddiu8081** [comment]
感谢，我调整下

**Comment by ddiu8081** [comment]
fixed in v0.4.6
