### ISSUE TITLE
[Bug]: v0.4.5 部分关键字没有颜色

### ISSUE THREAD

**Issue by Lmmmmmm-bb** [moegi-design/vscode-theme#14]
v0.4.5 版本部分关键字没有颜色
![image](https://user-images.githubusercontent.com/54026110/210559962-91c44a59-387e-4177-9906-d34692db5347.png)
切换到 v0.4.4 正常
![image](https://user-images.githubusercontent.com/54026110/210560092-e313913a-0410-4c1f-b3ad-45754208364b.png)

**Comment by ddiu8081** [comment]
感觉大面积黄色和其他颜色搭配不是太好，所以 v0.4.5 整体去掉了代表变量的黄色；
v0.4.6 做了些改动，把一部分黄色加回来了，可以再试下

**Comment by ikexing-cn** [comment]
关键字白色还是太不舒服了，我现在完全是回退版本使用的
看着真挺难受的（

**Comment by Lmmmmmm-bb** [comment]
+1，这部分关键字是否可以考虑其他颜色搭配
主要原因是**白色**作为关键字颜色的话容易和普通 Text 混淆，不好区分

**Comment by ddiu8081** [comment]
这两天我再调整看看

**Comment by ddiu8081** [comment]
在试着重新选取大部分颜色，去掉原来的紫色/蓝色部分，把紫色留给变量。草稿：

<img width="733" alt="ScreenShot 2023-02-14 at 00 08 02@2x" src="https://user-images.githubusercontent.com/1998168/218510352-e324ed26-2d58-4a27-bd2e-0b99fe72bdbd.png">

**Comment by Lmmmmmm-bb** [comment]
> 在试着重新选取大部分颜色，去掉原来的紫色/蓝色部分，把紫色留给变量。草稿：
> 
> <img alt="ScreenShot 2023-02-14 at 00 08 02@2x" width="733" src="https://user-images.githubusercontent.com/1998168/218510352-e324ed26-2d58-4a27-bd2e-0b99fe72bdbd.png">

wow 辛苦了，这个颜色看着舒服~

**Comment by ikexing-cn** [comment]
> 在试着重新选取大部分颜色，去掉原来的紫色/蓝色部分，把紫色留给变量。草稿：
> 
> <img alt="ScreenShot 2023-02-14 at 00 08 02@2x" width="733" src="https://user-images.githubusercontent.com/1998168/218510352-e324ed26-2d58-4a27-bd2e-0b99fe72bdbd.png">

组件和html标签能用两种颜色吗
就像vitess那样，这样有助于快速分清
