### ISSUE TITLE
Comment color in Zen theme is very low contrast

### ISSUE THREAD

**Issue by kkga** [moegi-design/vscode-theme#20]
It feels that the current comment color in Black Zen is unnecessarily dark, compared to the (non-Zen) Black theme:

https://github.com/moegi-design/vscode-theme/blob/0fb906b2727e6447dfa14ab06c70243749f8ef38/themes/moegi-black-zen-color-theme.json#L242

Black Zen:
<img width="648" alt="image" src="https://user-images.githubusercontent.com/1460122/221421802-5830c90a-158b-46f4-9049-a3f37daba74f.png">

Black:
<img width="648" alt="image" src="https://user-images.githubusercontent.com/1460122/221421847-dff97aee-3e8d-4137-be72-792552e5dc0b.png">

Both Black and Dark themes use a different shade of gray, so maybe it's worth using the same for Zen?

https://github.com/moegi-design/vscode-theme/blob/0fb906b2727e6447dfa14ab06c70243749f8ef38/themes/moegi-dark-color-theme.json#L242

https://github.com/moegi-design/vscode-theme/blob/0fb906b2727e6447dfa14ab06c70243749f8ef38/themes/moegi-black-color-theme.json#L242

**Comment by ddiu8081** [comment]
Yes, I think you are right, the comment color is indeed so dark. Thanks!

There's a bit of work to do next before going live. The color of keywords(`#747476`) is needed to be adjusted, otherwise they would be similar to the comments.
