### ISSUE TITLE
Support for rust

### ISSUE THREAD

**Issue by hnlcf** [moegi-design/vscode-theme#4]
Now the highlight color of Rust is confusing, and it is far from the ideal preview.

![image](https://user-images.githubusercontent.com/89689286/201020859-c480fae4-b529-4340-8f6a-237764e6e8e6.png)

![image](https://user-images.githubusercontent.com/89689286/201021195-46de42a9-1022-451f-9ea3-d773b5292fbb.png)

![image](https://user-images.githubusercontent.com/89689286/201021096-4dce4aab-f914-49db-b171-5095241fa079.png)

Main color is cold.

**Comment by ddiu8081** [comment]
Yes, it looks not good, it seems that it is different than other languages' highlighting schemes. I'll check it later.

**Comment by ddiu8081** [comment]
might fixed in v0.1.7
