### ISSUE TITLE
输入框输入时有虚影

### ISSUE THREAD

**Issue by molychn** [moegi-design/vscode-theme#6]
<img width="300" alt="233333" src="https://user-images.githubusercontent.com/46530729/202857846-704c36a9-daea-4f99-876a-afd4575d57a0.png">

**Comment by molychn** [comment]
<img width="308" alt="image" src="https://user-images.githubusercontent.com/46530729/202857970-49ad8cc8-2471-4839-ac71-0fc96bd58bdd.png">
这是其他主题输入时正常状态

**Comment by ddiu8081** [comment]
fixed in v0.2.3
