### ISSUE TITLE
Error when setting color of constant variables

### ISSUE THREAD

**Issue by wzunknown** [moegi-design/vscode-theme#7]
The color of constant variables in python is not working fine if I set it by "textMateRules"
like
![image](https://user-images.githubusercontent.com/32328286/205257095-a85fd813-0d3f-4feb-83d8-8af8ec2d2bec.png)

![image](https://user-images.githubusercontent.com/32328286/205257031-106b07dc-1ad0-4ed8-a79c-4f4b077f1b90.png)

**Comment by ddiu8081** [comment]
Looks like your might adjust semantic token colors in your `settings.json` and they override `textMateRules`.

Check if your `settings.json` contains `editor.semanticTokenColorCustomizations`, then disable it.

**Comment by wzunknown** [comment]
Thanks. You are right. But after I comment `editor.semanticTokenColorCustomizations`, the default color from this color theme overrides my settings.
![image](https://user-images.githubusercontent.com/32328286/205269448-b7fcd595-7359-4c30-9264-0b0bd10bb16d.png)

**Comment by wzunknown** [comment]
https://github.com/moegi-design/vscode-theme/blob/a68ca1e35071d68442f4e9cf2beb67fece49792a/themes/moegi-dark-color-theme.json#L236
maybe this line

**Comment by ddiu8081** [comment]
I'll disable them in next version, thanks!

**Comment by ddiu8081** [comment]
removed in v0.3.0
